# permissions for end users to view discconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discconfig-viewer-role
rules:
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - discconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - discconfigs/status
  verbs:
  - get
