# permissions for end users to edit diskconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diskconfig-editor-role
rules:
- apiGroups:
  - discoblocks.ondat.io
  resources:
  - diskconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discoblocks.ondat.io
  resources:
  - diskconfigs/status
  verbs:
  - get
