---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - discconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - discconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - discconfigs/status
  verbs:
  - get
  - patch
  - update
