name: Vulnerability Scanning 

on: workflow_call 

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:

      - name: log in to ghrc.io 
        uses: docker/login-action@1edf6180e07d2ffb423fc48a1a552855c0a1f508
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@f39d29766a1eb7432c47f6bb7b64ed70b2241524
        with:
          image-ref: ghcr.io/ondat/discoblocks:${{ github.sha }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@1fc1008278d05ba9455caf083444e6c5a1a3cfd8
        with:
          sarif_file: 'trivy-results.sarif'
